const moo = require('moo');

let lexer = moo.compile({
  NL: { match: /\r?\n/, lineBreaks: true },
  forLoop: '_:',
  loop: /_/,
  inc: /\+\+/,
  dec: /--/,
  write: 'w',
  read: 'read',
  WS: /[ \t]+/,
  comment: /##.*/,
  number: /0|[1-9][0-9]*/,
  string: /"(?:\\["\\]|[^\n"\\])*"/,
  arrow: /=>/,
  identifier: /[a-zA-Z_]\w*/,
  assignment_symbol: /:=/,
  conditional: '?',
  greater_or_equal: />=/,
  less_or_equal: /<=/,
  greater: />/,
  less: /</,
  equal: /==/,
  not_equal: /!=/,
  and: /&&/,
  or: /\|\|/,
  plus: /\+/,
  minus: /\-/,
  times: /\*/,
  divide: /\//,
  modulo: /%/,
  fn: /f/,
  leftParan: '(',
  rightParan: ')',
  fnEnd: /:endf/,
  loopEnd: /:endl/,
  conditionalEnd: /:endc/,
  openTag: /<</,
  closeTag: />>/,
});

module.exports = lexer;
