const moo = require('moo');

let lexer = moo.compile({
  WS: /[ \t]+/,
  comment: /\/\/.*?$/,
  number: /0|[1-9][0-9]*/,
  string: /"(?:\\["\\]|[^\n"\\])*"/,
  lparen: '(',
  rparen: ')',
  lsqrbracket: '[',
  rsqrbracket: ']',
  NL: { match: /\n/, lineBreaks: true },
  var_declaration: /@/,
  identifier: /[a-zA-Z_]\w*/,
  assignment: /=/,
  array: /list/,
  boolean: /yes|no/,
  arrow: /=>/,
  function: /fn/,
  condition: /when/,
  else: /else/,
  loop: /while/,
  semicolon: /;/,
  plus: /\+/,
  minus: /-/,
  multiply: /\*/,
  divide: /\//,
  equals: /==/,
  greaterThan: />/,
  lessThan: /</,
  greaterOrEqual: />=/,
  lessOrEqual: /<=/,
  print: /print/,
});

module.exports = lexer;
