const moo = require('moo');

let lexer = moo.compile({
  WS: /[ \t]+/,
  comment: /\/\/.*?$/,
  number: /0|[1-9][0-9]*/,
  string: /"(?:\\["\\]|[^\n"\\])*"/,
  lparen: '(',
  rparen: ')',
  keyword: ['while', 'if', 'else', 'moo', 'cows'],
  NL: { match: /\n/, lineBreaks: true },
  var_declaration: /@/,
  identifier: /[a-zA-Z_]\w*/,
  assignment: /=/,
  boolean: /true|false/,
  loopFor: /->/,
  loopWhile: /=>/,
  conditionalIf: /\?\?/,
  conditionalElseIf: /<</,
  conditionalElse: />>/,
  func: /func/,
  openBrace: /{/,
  closeBrace: /}/,
  comma: /,/,
  semicolon: /;/,
  loopTo: /to/,
  loopUntil: /until/,
  plus: /\+/,
  minus: /-/,
  multiply: /\*/,
  divide: /\//,
  equals: /==/,
  greaterThan: />/,
  lessThan: /</,
  greaterOrEqual: />=/,
  lessOrEqual: /<=/,
});

module.exports = lexer;
